# Header metadata

# Mind no '/' at the and of url
url: zakladpogrzebowykrokowa.pl

# Company name
companyName: Zakład Pogrzebowy Krokowa
companyFullName: Zakład Pogrzebowy Krokowa - Anna Pipka

title: Zakład Pogrzebowy Krokowa
description: Zakład Pogrzebowy Krokowa
keywords: Zakład Pogrzebowy, Usługi Pogrzebowe, Krokowa, Sprzedaż trumien, krzyży, tabliczek, urn, Całodobowy przewóz zmarłych, Obsługa pogrzebu, Kredytowanie pogrzebu, Własna chłodnia (gratis), Odzież dla osoby zmarłej, Kwiaty, Możliwość organizacji różańca (pustej nocy) w kaplicy, Oprawa muzyczna pogrzebu (trąbka) oraz nagłośnienie na cmentarzu, Kremacja
author: Anna Pipka

google_site_verification: 8MrLTVfPuvD4nb2LhLsnpu_N7pNAbyJIN2C3vG59lKU
google_map_apikey: AIzaSyA0EKWuHUersacG87bmEkcb6r5LYagZy84

analytics: 
    code: UA-48118584-1
    domain: zakladpogrzebowykrokowa.pl
  
# Social media
social:
    gplus: https://www.google.com/+ZakladPogrzebowyKrokowaPL
  
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Warsaw

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/