# Header metadata

url: zakladpogrzebowykrokowa.pl

title: Zakład Pogrzebowy Krokowa
description: Zakład Pogrzebowy Krokowa
author: Anna Pipka

og_site_name: Zakład Pogrzebowy Krokowa

google_site_verification: 8MrLTVfPuvD4nb2LhLsnpu_N7pNAbyJIN2C3vG59lKU

analytics: 
    code: UA-48118584-1
    domain: zakladpogrzebowykrokowa.pl
  
# Social media
social:
    gplus   : https://plus.google.com/116013958524059471308
  
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Warsaw

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/