# Header metadata

# Mind no '/' at the and of url
url: zakladpogrzebowykrokowa.pl

# Company name
companyName: Zakład Pogrzebowy Krokowa
companyFullName: Zakład Pogrzebowy Krokowa - Anna Pipka

title: Zakład Pogrzebowy Krokowa A.Pipka
description: Zakład Pogrzebowy Krokowa A.Pipka
author: Anna Pipka



google_site_verification: 8MrLTVfPuvD4nb2LhLsnpu_N7pNAbyJIN2C3vG59lKU
google_map_apikey: AIzaSyA0EKWuHUersacG87bmEkcb6r5LYagZy84

analytics: 
    code: UA-48118584-1
    domain: zakladpogrzebowykrokowa.pl
  
# Social media
social:
    gplus: https://plus.google.com/116013958524059471308
  
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Warsaw

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/